# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from AlgoTrader import *
from AlgoTrader import AlgoTrader

bot = AlgoTrader()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sellQuantityLabel = QtWidgets.QLabel(self.centralwidget)
        self.sellQuantityLabel.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.sellQuantityLabel.setFont(font)
        self.sellQuantityLabel.setObjectName("sellQuantityLabel")
        self.buyQuantity = QtWidgets.QSpinBox(self.centralwidget)
        self.buyQuantity.setGeometry(QtCore.QRect(110, 20, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.buyQuantity.setFont(font)
        self.buyQuantity.setProperty("value", 25)
        self.buyQuantity.setObjectName("buyQuantity")
        self.buyQuantityLabel = QtWidgets.QLabel(self.centralwidget)
        self.buyQuantityLabel.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.buyQuantityLabel.setFont(font)
        self.buyQuantityLabel.setObjectName("buyQuantityLabel")
        self.movingAveragesButton = QtWidgets.QPushButton(self.centralwidget)
        self.movingAveragesButton.setGeometry(QtCore.QRect(170, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.movingAveragesButton.setFont(font)
        self.movingAveragesButton.setObjectName("movingAveragesButton")
        self.movingAveragesButton.clicked.connect(self.tradeByMovingAverages)
        self.stocksList = QtWidgets.QTextEdit(self.centralwidget)
        self.stocksList.setGeometry(QtCore.QRect(20, 80, 471, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.stocksList.setFont(font)
        self.stocksList.setObjectName("stocksList")
        self.stocksList.setText("")
        self.sellQuantity = QtWidgets.QSpinBox(self.centralwidget)
        self.sellQuantity.setGeometry(QtCore.QRect(110, 50, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.sellQuantity.setFont(font)
        self.sellQuantity.setProperty("value", 25)
        self.sellQuantity.setObjectName("sellQuantity")
        self.volumeButton = QtWidgets.QPushButton(self.centralwidget)
        self.volumeButton.setGeometry(QtCore.QRect(300, 40, 91, 31))
        self.volumeButton.clicked.connect(self.tradeByVolume)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.volumeButton.setFont(font)
        self.volumeButton.setObjectName("volumeButton")
        self.growthButton = QtWidgets.QPushButton(self.centralwidget)
        self.growthButton.setGeometry(QtCore.QRect(400, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.growthButton.setFont(font)
        self.growthButton.setObjectName("growthButton")
        self.growthButton.clicked.connect(self.tradeByGrowth)
        self.methodLabel = QtWidgets.QLabel(self.centralwidget)
        self.methodLabel.setGeometry(QtCore.QRect(170, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.methodLabel.setFont(font)
        self.methodLabel.setObjectName("methodLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.loadStocksList()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Algo Trader"))
        self.sellQuantityLabel.setText(_translate("MainWindow", "Sell Quantity"))
        self.buyQuantityLabel.setText(_translate("MainWindow", "Buy Quantity"))
        self.movingAveragesButton.setText(_translate("MainWindow", "Moving Averages"))
        self.volumeButton.setText(_translate("MainWindow", "Volume"))
        self.growthButton.setText(_translate("MainWindow", "Coming Soon"))
        self.methodLabel.setText(_translate("MainWindow", "Trade by..."))

    def loadStocksList(self):
        with open('symbols.txt', mode='r') as file:
            stocks = file.read()
            self.stocksList.setText(stocks)

    def saveStocksList(self):
        with open('symbols.txt', mode='w') as file:
            file.write(self.stocksList.toPlainText())
            file.close()

    def tradeByMovingAverages(self):
        self.saveStocksList()
        bot.tradeByMovingAverages()
    
    def tradeByVolume(self):
        self.saveStocksList()
        bot.tradeByVolume()

    def tradeByGrowth(self):
        self.saveStocksList()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ret = app.exec_()
    ui.saveStocksList()
    sys.exit(ret)
